on:
  workflow_dispatch: 
permissions: write-all

jobs:
  arch:
    runs-on: ubuntu-latest
    env:
      A: ${{ github.actor }}
      B: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: sudo hostnamectl set-hostname archlinux
      - run: curl -fsSL https://tailscale.com/install.sh | sh
      - run: sudo tailscale up --auth-key=tskey-auth-kgQPfiVxo721CNTRL-We491WrBj6U42gmf1E4K7ULHNC4JjvEVD
      - run: sudo swapoff -a
      - run: sudo fallocate swap -l 8G
      - run: sudo mkswap swap
      - run: sudo swapon swap
      - run: docker run -itd -p 1111:22 -p 2222:2222 --name arch ghcr.io/ambitious2coil3/archlinux:latest sh -c "/usr/bin/sshd -D"
      - run: sleep 200
      - run: docker stop arch
      - run: docker export arch | docker import - ghcr.io/ambitious2coil3/archlinux:latest
      - run: docker login ghcr.io -u $A -p $B
      - run: docker push ghcr.io/ambitious2coil3/archlinux:latest
