on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: |
          cd
          gh repo clone Ambitious2Coil3/a
          touch file12345
          git add .
          git commit -m "hi"
          git push
