on:
  schedule:
    - cron: "0 * * * *"
  workflow_call:
  workflow_dispatch:
jobs:
  this:
   runs-on: uubuntu-latest
   steps:
     - run: sudo apt install stress-ng
     - run: stress-ng --cpu 0 --timeout 6h
     
