on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: ifconfig
      - run: sleep 60
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: ifconfig
      - run: sleep 30
