on:
  workflow_dispatch:
    inputs:
      container:
        required: true
        type: string
      delay:
        required: true
        type: number
      ports:
        required: true
        type: number
      extraports:
        required: false
        type: string
      command:
        required: true
        type: string
      hostname:
        required: true
        type: string
permissions: write-all
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      A: ${{ github.actor }}
      B: ${{ secrets.GITHUB_TOKEN }}
      C: ${{ inputs.container }}
      D: ${{ inputs.delay }}
      E: ${{ inputs.ports }}
      F: ${{ inputs.command }}
      G: ${{ inputs.extraports }}
      H: ${{ inputs.hostname }}
    steps:
      - run: sudo hostnamectl set-hostname vm$H
      - run: curl -fsSL https://tailscale.com/install.sh | sh
      - run: sudo tailscale up --auth-key=tskey-auth-kgQPfiVxo721CNTRL-We491WrBj6U42gmf1E4K7ULHNC4JjvEVD
      - run: echo "runner:1" | sudo chpasswd
      - run: docker login ghcr.io -u $A -p $B
      - run: docker run --privileged -itd -p $E:$E $G --name $C ghcr.io/ambitious2coil3/$C $F
      - run: sleep $D
      - run: docker stop $C
      - run: docker export $C | docker import - ghcr.io/ambitious2coil3/$C
      - run: docker push ghcr.io/ambitious2coil3/$C
