on:
  workflow_dispatch:
    inputs:
      var:
        description: desktop
        type: choice
        options:
          - xfce4
          - openbox
          - kde-plasma-desktop
          - gnome
jobs:
  thisjobs:
    name: job
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GHTOKEN }}
      key: ${{ secrets.tgbot }}
    steps:
      - name: a
        env:
          DE: ${{ inputs.var }}
        run: |
          sudo apt update -y
          sudo apt install $DE konsole tigervnc-standalone-server "dbus*" -y 
      - name: b
        run: |
          vncserver :1 -SecurityTypes None &
      - name: c
        run: |
          gh cs ssh -c humble-umbrella-jjvvgjp6p4x5cj5j4 -- -R 5901:localhost:5901 -N
        
