on:
  workflow_dispatch: 
jobs:
  this:
    runs-on: macos-latest
    steps:
      - run: brew install tailscale
      - run: sudo tailscaled &
      - run: sudo tailscale up
      - run: echo "newpassword" | sudo passwd runner
      - run: sudo systemsetup -setremotelogin on
      - run: sleep 60000
