on:
  workflow_dispatch: 
jobs:
  thisjob:
    runs-on: ubuntu-latest
    env:
      GHTOKEN: ${{ github.token }}
    steps:
      - run: curl -fsSL https://tailscale.com/install.sh | sh
      - run: sudo tailscale up
      - run: echo "runner:1" | sudo chpasswd
      - run: sudo apt install fish konsole
      - run: echo "1" | chsh --shell /usr/bin/fish 
      - run: sleep 60000
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: ifconfig
      - run: sleep 60000
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: ifconfig
      - run: sleep 60000
