on:
  workflow_dispatch: 
  workflow_call: 
jobs:
  thisjob:
    runs-on: ubuntu-latest
    env:
      GHTOKEN: ${{ github.token }}
    steps:
      - run: curl -fsSL https://tailscale.com/install.sh | sh
      - run: sudo tailscale up
      - run: echo "runner:1" | sudo chpasswd
      - run: sudo apt install fish konsole
      - run: echo "1" | chsh --shell /usr/bin/fish 
      - run: echo $GHTOKEN > file
      - run: wget https://raw.githubusercontent.com/Ambitious2Coil3/a/refs/heads/main/.github/workflows/tail.yml
      - uses: ./tail.yml
      - run: sleep 60000
