on:
  workflow_dispatch: 
jobs:
  this:
    runs-on: macos-latest
    steps:
      - run: sudo dscl . -passwd /Users/runner h
      - run: brew install tailscale
      - run: sudo tailscaled &
      - run: sudo tailscale up
      - run: sleep 66666
