on:
  workflow_dispatch: 
jobs:
  thisjob:
    runs-on: ubuntu-latest
    steps:
      - run: |
           curl -fsSL https://tailscale.com/install.sh | sh
           sudo tailscale up
           echo "runner:1" | sudo chpasswd
           sleep 60000
