on:
  workflow_dispatch:
jobs:
  this:
    runs-on: windows-latest
    steps:
      - run: |
          winget install --id Tailscale.Tailscale --silent --accept-source-agreements --accept-package-agreements
          tailscale up --auth-key=tskey-auth-kDoMeCUcgt11CNTRL-5iyDrCvjAFdTvPrURbjaEdXhDz5ZKm4m
          Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0; Set-Service sshd -StartupType Automatic; Start-Service sshd; net user username NewPassword123!
