on:
  workflow_dispatch:
jobs:
  this:
    runs-on: windows-latest
    steps:
      - run: winget install --id Tailscale.Tailscale --silent --accept-source-agreements --accept-package-agreements; Set-Service Tailscale -StartupType Automatic; Start-Service Tailscale; & "$env:ProgramFiles\Tailscale\tailscale.exe" up --auth-key=tskey-auth-kDoMeCUcgt11CNTRL-5iyDrCvjAFdTvPrU
      - run: Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0; Set-Service sshd -StartupType Automatic; Start-Service sshd; net user username NewPassword123!
      - run: Start-Sleep -Seconds 500
